config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'users/:id/setlists' => 'setlists#index'
  get 'setlist/:id/edit' => 'setlists#edit'

  post 'songs/show' => 'songs#show'
  post 'song/new' => 'songs#show'

  post 'setlist/new' => 'setlists#show'
  post 'setlists/:id/edit' => 'setlists#add_song', as: 'add_song'
  post 'setlists/:id' => 'songs#new_song', as: 'new_song'
  post 'setlists/:id' => 'setlists#edit'

  post 'users/:id/songs' => 'songs#index'

  post '' => 'songs#create'
  patch 'songs' => 'songs#index'

  delete 'song/:id/edit' => 'songs#destroy', as: 'destroy'
  delete 'setlist/:id/edit' => 'setlists#destroy_song', as: 'destroy_song'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :songs

  resources :setlists do
    resources :songs, except: [:index]
  end
end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
    belongs_to :user
    has_many :setlist_songs
    has_many :songs, through: :setlist_songs

    def songs_attributes=(songs_attributes)
        songs_attributes.values.each do |songs_attributes|
          if !songs_attributes["title"].empty?
            self.songs.build(songs_attributes)
          end
        end
      end
end

app/models/setlist_song.rb
class SetlistSong < ActiveRecord::Base
    belongs_to :song
    belongs_to :setlist
end

app/models/song.rb
class Song < ActiveRecord::Base
    belongs_to :user
    has_many :setlist_songs
    has_many :setlists, through: :setlist_songs
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: %i[github]

  has_many :setlists
  has_many :songs

  def self.from_omniauth(auth)
    if user = User.where(email: auth['info']['email']).first
      user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
        u.email = auth.info.email
        u.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if current_user
      render :user_home
    else
      render :index
    end
  end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @setlists = current_user.setlists.all
    respond_to do |format|
      format.html {render :index, :layout => false}
      format.json {render json: @setlists}
    end
  end

  def show
    @setlist = Setlist.find(params[:id])
     respond_to do |format|
       format.html {render :show, :layout => false}
       format.json {render json: @setlist}
       end
  end

  def new
    @setlist = Setlist.new
    render :new, :layout => false
  end

  def create
    @setlist = Setlist.new(setlist_params)
    @setlist.user_id = current_user.id
      if @setlist.save
        redirect_to root_path
      else
        render :new
    end
  end

  def edit
    @setlist = Setlist.find(params[:id])
  end

  def update
    @setlist = Setlist.find(params[:id])
      if @setlist.update(setlist_params)
        redirect_to setlist_path
      else
        render :edit
    end
  end

  def add_song
    @songs = current_user.songs.all
    @setlist = Setlist.find(params[:id])
    @song = Song.find(params[:id])
    @setlist_song = SetlistSong.new
      if !@songs.present?
        flash[:no_songs] = "You have no songs! Add a song first - then you can add it them to your setlist."
      end
    @setlist_song.setlist_id = @setlist.id
    @setlist_song.song_id = @song.id
    @setlist_song.save
    render :show
  end

  def destroy_song
      @setlist = Setlist.find(params[:id])
      @setlist.songs.destroy(params[:song_id])
      render :edit
  end

  def destroy
      @setlist = Setlist.find(params[:id])
      @setlist.destroy
      render :index
  end


    private


  def setlist_params
      params.require(:setlist).permit(:name, :comments, :user_id, songs_attributes: [:title, :artist, :comments, :song_url, :song_id, :user_id])
  end

  def setlist_song_params
      params.require(:setlist_songs).permit(:setlist_id, :song_id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
        @songs = current_user.songs.all
        respond_to do |format|
          format.html {render :index}
          format.json {render json: @songs}
         end
       end

      def show
        @song = Song.find(params[:id])
         respond_to do |format|
           format.html {render :show, layout: false}
           format.json {render json: @song}
         end
      end


      def new
        @song = Song.new
        render :new, :layout => false
      end

      def create
        @song = current_user.songs.build(song_params)
        @song.save
        respond_to do |format|
          format.html {redirect_to root_path}
          format.json {render json: @song}
         end
      end

    #   def new_song
    #     @song = Song.create(song_params)
    #     @setlist_song = SetlistSong.create(song_id: @song.id, setlist_id: params[:id])
    #
    #     @setlist_song.save
    #
    #     respond_to do |format|
    #       format.html {render :index, layout: false}
    #       format.json {render json: @song}
    #
    #      end
    #
    #
    # end

      def edit
        @song = Song.find(params[:id])

        respond_to do |format|
          format.html {render :edit, layout: true}
          format.json {render json: @song}
        end
      end

      def update
        @song = Song.find(params[:id])
          if @song.update(song_params)
            redirect_to root_path
          else
            render :edit
        end
      end

      def destroy
        @song = Song.find(params[:id])
        @song.destroy
        render :index
      end

      private

      def song_params
        params.require(:song).permit(:title, :artist, :comments, :song_url, :user_id)
      end
    end

app/controllers/users.rb
class Users < ApplicationController

  def index

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def github
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
      else
        session["devise.github_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<div class="flex-row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <h1>Welcome to Setlist Maker</h1>
    <br>
    <h4>Collaberate on setlists and invite people to add songs with no sign-up required. From YouTube, Spotify, SoundCloud, etc. Share groups of songs from any platform. </h4>
    <br>

    <img src="../../assets/setlist.jpeg" class="img-fluid banner" alt="Responsive image"></div>
  </div>
</div>

app/views/home/user_home.html.erb
<div class="flex-row">
  <div class="col-xs-1"></div>

  <div class="col-xs-5">
    <h2>Your Setlists</h2>
      <button type=button><%= link_to "New Setlist", { :controller => :setlists, :action => :new }, class: "link_to_setlist_form" %></button>
      <div class="new_setlist_form"></div>
    <br>
    <% current_user.setlists.each do |s| %>
      <div id="setlist-<%= s.id %>" data-id="<%= s.id %>">
        <a class="load_setlist_songs" href="/setlists/<%=s.id%>" ><br>
          <%= s.name %><br>
        </a>
      </div>
    <%end%>
    <br>
  </div>

  <div class="col-xs-5">
    <div class="list_setlist_songs"></div>
  </div>

  <div class="col-xs-1"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SetlistMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button
          type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        </button>
        <a class="navbar-brand" href="/">Setlist Maker</a>

      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">


        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="navbar-text"><p>Signed in as <%= current_user.email%><p></li>
          <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete %></li>
            <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/setlists/_form.html.erb
<form>
<div class = "field">
<%= f.label :name %>
<%= f.text_field :name %>
</div>

<div class = "field">
<%= f.label :comments %>
<%= f.text_field :comments %>
</div>

<div class = "actions">

</div>

app/views/setlists/edit.html.erb
<div class="col-xs-2"></div>
  <div class ="col-xs-8">

    <p>Edit Setlist</p>

    <%= form_for (@setlist) do |f| %>
      <%= render 'form', f: f %>
      <%= f.submit %>
    <%end%>
    <%= button_to "Delete Setlist", {:controller => :setlists, :action => 'destroy' }, :method => :delete %>


    <br><br>
    <%=form_tag(controller: "setlists", action: "add_song") do %>
      <%# binding.pry %>
      <%=select('@songs', '@songs.ids', options_for_select(current_user.songs.collect{ |s| [s.title, s.id] })) %>
      <%= flash[:no_songs] %>
      <%= submit_tag('Add Song To Setlist')  %>
    <%end%>

    <% @setlist.songs.each do |s|%>
      <li> <%= s.title%> <%= button_to "delete", {:controller => :setlists, :song_id => s.id, :action => 'destroy_song' }, :method => :delete %>
      <br>
    <%end%>

  </div>

<div class="col-xs-2"></div>

app/views/setlists/index.html.erb
<p>Your Setlists</p>

<% current_user.setlists.each do |s| %>
  <div id="setlist-<%= s.id %>" data-id="<%= s.id %>">
    <a class="load_setlist_songs" href="/setlists/<%=s.id%>" ><br>
    <%= s.name %><br>
    <%= s.comments %><br>
  </div> <br>

  <br>
<%end%>

<%= link_to "New Setlist", new_setlist_path(current_user.setlists.new) %>

app/views/setlists/new.html.erb
<!-- <div class="col-xs-2"></div>
  <div class="col-xs-8">

    <h2>New Setlist</h2> -->
    <%= form_for @setlist do |f|%>
      <%= render 'form', f: f %>
      <%= f.fields_for :songs, @setlist.songs.build do |r| %>
      <%= f.submit %>
      <br><br>


      <%end%>
    <%end%>

  <!-- </div>

<div class="col-xs-2"></div> -->

app/views/setlists/show.html.erb
<div class="flex-row">
  <div class="col-xs-1"></div>
    <div class="col-xs-5">

      <div class="info">
        <h2 class="bold"><%= @setlist.name %> </h2> <br><br>
      </div>

      <div id="setlist-<%=@setlist.id%>-songs">
        <%# binding.pry %>
      <% @setlist.songs.each do |s|%>
        <div id="song-<%=s.id%>">
          <h3><a href="<%=s.song_url%>"><%= s.title%></a></h3> - <%= link_to "remove", destroy_song_path(@setlist), :class => "destroy_song" %>

          <%end%>

        </div>
      </div>
    </div>


      <div class="col-xs-5">
        <% if current_user %>
              <%= link_to "Edit setlist", edit_setlist_path(@setlist) , :class => "edit_song" %></p>
            <% else %>
              <%= link_to "Create Your Own Account", new_user_registration_path %>
              </form>
        <% end %>


      <br><br>

      <div class="col-xs-1"></div>
    </div>

  </div>

app/views/songs/_form.html.erb
<form>
<div class = "field">
<%= f.label :title %>
<%= f.text_field :title %>
</div>

<div class = "field">
<%= f.label :artist %>
<%= f.text_field :artist %>
</div>

<div class = "field">
<%= f.label :comments %>
<%= f.text_field :comments %>
</div>

<div class = "field">
<%= f.label :song_url %>
<%= f.text_field :song_url %>
</div>

<%= f.hidden_field :user_id, :value => current_user.id %>
<!-- <%= f.hidden_field :song_id, :value => Song.new.id %> -->
<!-- <div id="song-id" data-id="<%= Song.new.id %>"></div> -->
</div>

app/views/songs/edit.html.erb
<div class="col-xs-1"></div>
  <div class="col-xs-10">

  <p>Edit Song</p>

  <%= form_for (@song) do |f| %>
  <%= render 'form', f: f %>
    <%= f.submit %>
    <%end%>

    <%= button_to "Delete", {:controller => :songs, :id => @song.id, :action => 'destroy' }, :method => :delete %>

</div>

app/views/songs/index.html.erb
<div class="song-titles">
  <br>
  <% current_user.songs.reverse.each do |song| %>

  <div id="song-<%= song.id %>">
    <li><a
      class="song-link"
      data-id="<%= song.id %>"
      href="songs/<%=song.id %>">
      <%= song.title %></a><br></li>
    <li><a
      href="<%=song.song_url %>"
      target="_blank">Link to Listen</a></li>
        <div id="song-<%= song.id %>-details"></div>
      </div>
    <br>
  <% end %>
</div>

app/views/songs/new.html.erb
<%= form_for(@song) do |f| %>
<%= render 'form', f: f %>

<%= f.submit %>

<%end%>

app/views/songs/show.html.erb
<!-- <% if false %> -->
<div class="song-info">

Name: <%= @song.title %><br>
Artist: <%= @song.artist %><br>
Comments: <%= @song.comments %><br>
<a href="<%=@song.song_url%>"target="_blank"> Link to song </a>



<% if @current_user %>

      <form action="/songs/new" method="post">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
        <%= tag(:input, :type => "hidden", :name => :user_id, :value => current_user.id) %>
        <%= tag(:input, :type => "hidden", :name => :song_id, :value => @song.id) %>
      </form>
    <% end %>

  </div>
 <% end %>